### PR TITLE
PROJ-114 - increased timeout to 1s

### PR DESCRIPTION
**Pull request by brampauwelyn**
### Changed
- increased timeout to 1s

---
Ticket: [https://jira.uitdatabank.be/browse/PROJ-114](https://jira.uitdatabank.be/browse/PROJ-114)

### CODE REVIEW

**Comment by bertramakers** [comment]
I mentioned in #31 that this is an arbitrary amount of time to wait and will never be 100% correct. Instead we should look into a real fix, like polling for the insightly id on the dashboard instead. If not, the next PR will be to increase this to two or three seconds. At which point it's going to be too slow for our end users and the app will seem unresponsive.

**Comment by jdrieghe** [comment]
@bertramakers makes a good point here. Let's take a bit of extra time to come up with a thorough solution.

**Comment by brampauwelyn** [comment]
> @bertramakers makes a good point here. Let's take a bit of extra time to come up with a thorough solution.

@jdrieghe,
I agree with both of you. I've discussed this with Corneel and this is something we're going to pick-up later. He needs to verify the budget. I created a ticket for this improvement:
[https://jira.uitdatabank.be/browse/PROJ-119](https://jira.uitdatabank.be/browse/PROJ-119)

**Comment by bertramakers** [comment]
@brampauwelyn sorry for the late reply. As I was on holiday and we had the retreat immediately after that I was not able to take a look at your comment earlier. I see that PROJ-119 is now in ready for development with the necessary labels. Can we close this and fix it correctly in PROJ-119? As it's been 21 days since your comment I assume increasing the timeout is not that urgent and we can afford to take some more time to fix it thoroughly.

**Pull request closed without merging**
