### PR TITLE
PROJ-141 altered modal to show a refresh link

### PR DESCRIPTION
**Pull request by simonpubliq**
### Added
altered modal to show a refresh link

Schermafbeelding 2020-06-25 om 14 21 21

---
Ticket: https://jira.uitdatabank.be/browse/PROJ-141

### CODE REVIEW

**Comment by simonpubliq** [comment]
Node version raise was needed to fix this error:
Schermafbeelding 2020-06-25 om 14 25 16

**Comment by bertramakers** [comment]
It's not normal for node to "suddenly" have to be updated. I think the actual issue is that a dependency of `grunt-cli`, which we install here without a specific version, has dropped support for node 6? https://github.com/cultuurnet/projectaanvraag-angular/blob/master/.travis.yml#L7 So maybe we should pin `grunt-cli` to a version which relies on an older version of `mkdirp`?

**Comment by bertramakers** [comment]
This seems to be the culprit: https://gruntjs.com/blog/2020-03-16-grunt-1.1.0-released

> Update to mkdirp ~1.0.3
> Only support versions of Node >= 8

I know ideally we'd update to Node 8+ but that is a change we need to investigate into more detail because then we need to make sure Jenkins etc also use Node 8 (and I'm not sure UDB3 supports that at this point).

**Comment by simonpubliq** [comment]
> It's not normal for node to "suddenly" have to be updated. I think the actual issue is that a dependency of `grunt-cli`, which we install here without a specific version, has dropped support for node 6? https://github.com/cultuurnet/projectaanvraag-angular/blob/master/.travis.yml#L7 So maybe we should pin `grunt-cli` to a version which relies on an older version of `mkdirp`?

That's also an option. The problem you mentioned about 'mkdirp' is indeed why I updated.

**Comment by bertramakers** [comment]
I've created a separate PR to fix the Travis issue: https://github.com/cultuurnet/projectaanvraag-angular/pull/43
Can you revert your changes to the node version in this one @simonpubliq ?

**Pull request merged**
