### PR TITLE
Add meta description in head section

### PR DESCRIPTION
**Pull request by LucWollants**
### Added
- Add meta description in head section
---
Ticket: https://jira.uitdatabank.be/browse/PROJ-137

### CODE REVIEW

**Review by bertramakers — APPROVED** [review]
Just wondering if this should be part of the config so it can easily be changed later without a code change?

**Comment by jdrieghe** [comment]
@bertramakers we can do that the third time a change is requested. YAGNI and all that :D

**Review by jdrieghe — APPROVED** [review]

**Comment by bertramakers** [comment]
Makes sense :)

**Comment by bertramakers** [comment]
I think a key in yagni is this though:

> It is meant to be used in combination with several other practices, such as continuous refactoring, continuous automated unit testing, and continuous integration. Used without continuous refactoring, it could lead to disorganized code and massive rework, known as technical debt.

Which we do so we can indeed leave it like this, but I'm used to other projects that get built once and then neglected for the most part so I sometimes tend to err on the side of caution ;)

**Pull request merged**
